/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppRecipesRecipeIdIndexRouteImport } from './routes/_app/recipes/$recipeId/index'
import { Route as AppRecipesRecipeIdEditRouteImport } from './routes/_app/recipes/$recipeId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdIndexRoute = AppRecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdEditRoute = AppRecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AppLoginRoute
  '/r/$slug': typeof RSlugRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AppLoginRoute
  '/r/$slug': typeof RSlugRoute
  '/': typeof AppIndexRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/r/$slug': typeof RSlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/_app/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/r/$slug'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/r/$slug'
    | '/'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/login'
    | '/r/$slug'
    | '/_app/'
    | '/_app/recipes/new'
    | '/_app/recipes/$recipeId/edit'
    | '/_app/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/': {
      id: '/_app/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AppRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/edit': {
      id: '/_app/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLoginRoute: typeof AppLoginRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppRecipesRecipeIdEditRoute: typeof AppRecipesRecipeIdEditRoute
  AppRecipesRecipeIdIndexRoute: typeof AppRecipesRecipeIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLoginRoute: AppLoginRoute,
  AppIndexRoute: AppIndexRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppRecipesRecipeIdEditRoute: AppRecipesRecipeIdEditRoute,
  AppRecipesRecipeIdIndexRoute: AppRecipesRecipeIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
