/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppAuthedRouteImport } from './routes/_app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/_app/_authed/index'
import { Route as AppAuthedRecipesNewRouteImport } from './routes/_app/_authed/recipes/new'
import { Route as AppAuthedRecipesRecipeIdIndexRouteImport } from './routes/_app/_authed/recipes/$recipeId/index'
import { Route as AppAuthedRecipesRecipeIdEditRouteImport } from './routes/_app/_authed/recipes/$recipeId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedRecipesNewRoute = AppAuthedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedRecipesRecipeIdIndexRoute =
  AppAuthedRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedRecipesRecipeIdEditRoute =
  AppAuthedRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AppAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppAuthedIndexRoute
  '/login': typeof AppLoginRoute
  '/r/$slug': typeof RSlugRoute
  '/recipes/new': typeof AppAuthedRecipesNewRoute
  '/recipes/$recipeId/edit': typeof AppAuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof AppAuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppAuthedIndexRoute
  '/login': typeof AppLoginRoute
  '/r/$slug': typeof RSlugRoute
  '/recipes/new': typeof AppAuthedRecipesNewRoute
  '/recipes/$recipeId/edit': typeof AppAuthedRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AppAuthedRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_authed': typeof AppAuthedRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/r/$slug': typeof RSlugRoute
  '/_app/_authed/': typeof AppAuthedIndexRoute
  '/_app/_authed/recipes/new': typeof AppAuthedRecipesNewRoute
  '/_app/_authed/recipes/$recipeId/edit': typeof AppAuthedRecipesRecipeIdEditRoute
  '/_app/_authed/recipes/$recipeId/': typeof AppAuthedRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/r/$slug'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/r/$slug'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_authed'
    | '/_app/login'
    | '/r/$slug'
    | '/_app/_authed/'
    | '/_app/_authed/recipes/new'
    | '/_app/_authed/recipes/$recipeId/edit'
    | '/_app/_authed/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed/': {
      id: '/_app/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/recipes/new': {
      id: '/_app/_authed/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppAuthedRecipesNewRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/recipes/$recipeId/': {
      id: '/_app/_authed/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AppAuthedRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/recipes/$recipeId/edit': {
      id: '/_app/_authed/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppAuthedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedRecipesNewRoute: typeof AppAuthedRecipesNewRoute
  AppAuthedRecipesRecipeIdEditRoute: typeof AppAuthedRecipesRecipeIdEditRoute
  AppAuthedRecipesRecipeIdIndexRoute: typeof AppAuthedRecipesRecipeIdIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedRecipesNewRoute: AppAuthedRecipesNewRoute,
  AppAuthedRecipesRecipeIdEditRoute: AppAuthedRecipesRecipeIdEditRoute,
  AppAuthedRecipesRecipeIdIndexRoute: AppAuthedRecipesRecipeIdIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
